	# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(:name => 'sample1',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'aa@aa.com',:password => 'sample',:age => '20代',:admin => 'true')
User.create(:name => 'sample2',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ii@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample3',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'uu@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample4',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ee@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample5',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'oo@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample6',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ka@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample7',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ki@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample8',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ku@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample9',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ke@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample10',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'ko@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample11',:sex => '男性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'sa@aa.com',:password => 'sample',:age => '20代')
User.create(:name => 'sample12',:sex => '女性',:introduction => 'hello',:address => '関東',:job => '会社員',:email => 'si@aa.com',:password => 'sample',:age => '20代')
Category.create(:category => '学習・勉強')
Category.create(:category => 'スポーツ・健康')
Category.create(:category => 'ものづくり')
Category.create(:category => '音楽')
Category.create(:category => '旅行')
Category.create(:category => '芸術・アート')
Category.create(:category => '料理・グルメ')
Category.create(:category => 'ビジネス')
Category.create(:category => 'ゲーム')
Category.create(:category => '収集')
Category.create(:category => '手品・マジック')
Category.create(:category => '写真・映像')
Category.create(:category => '執筆')
Category.create(:category => '観戦・鑑賞')
Category.create(:category => 'その他')
Hobby.create(:name => '野球',:category_id => '2',:introduction => '野球は１チーム9人で行う球技スポーツです。')
Hobby.create(:name => 'サッカー',:category_id => '2',:introduction => 'サッカーは１チーム11人で行う球技スポーツです。')
Hobby.create(:name => 'バスケットボール',:category_id => '2',:introduction => 'バスケットボールは１チーム5人で行う球技スポーツです。')
Hobby.create(:name => '卓球',:category_id => '2',:introduction => '卓球は1対1、もしくは2対2で行う球技スポーツです。')
Hobby.create(:name => '写真',:category_id => '12',:introduction => '写真')
Hobby.create(:name => '映画鑑賞',:category_id => '14',:introduction => '映画鑑賞')
Hobby.create(:name => 'ダーツ',:category_id => '9',:introduction => 'ダーツ')
Hobby.create(:name => '御朱印集め',:category_id => '5',:introduction => '御朱印集め')
Hobby.create(:name => '俳句',:category_id => '13',:introduction => '俳句')
Hobby.create(:name => 'オカリナ',:category_id => '4',:introduction => 'オカリナ')
Hobby.create(:name => 'アイドル',:category_id => '14',:introduction => 'アイドルファン')
Hobby.create(:name => '人間観察',:category_id => '15',:introduction => '人間観察')
Hobby.create(:name => '株',:category_id => '8',:introduction => '株')
Hobby.create(:name => 'パチンコ',:category_id => '15',:introduction => 'パチンコ')
Hobby.create(:name => '合コン',:category_id => '15',:introduction => '合コン')
Hobby.create(:name => 'タロットカード',:category_id => '15',:introduction => 'タロットカード')
Hobby.create(:name => 'ボルダリング',:category_id => '2',:introduction => 'ボルダリング')
Hobby.create(:name => 'DJ',:category_id => '4',:introduction => 'DJ')
Hobby.create(:name => '宝塚',:category_id => '14',:introduction => '宝塚')
Hobby.create(:name => 'DIY',:category_id => '3',:introduction => 'DIY')
Hobby.create(:name => '筋トレ',:category_id => '2',:introduction => '筋トレ')
Hobby.create(:name => '切手',:category_id => '10',:introduction => '切手')
Hobby.create(:name => 'お菓子作り',:category_id => '7',:introduction => 'お菓子作り')
Hobby.create(:name => '四国遍路',:category_id => '5',:introduction => '四国遍路')
Rating.create(:name => 'active')
Rating.create(:name => 'major')
Rating.create(:name => 'gain')
Rating.create(:name => 'appeal')
Rating.create(:name => 'health')
Rating.create(:name => 'relax')
Rating.create(:name => 'concentrate')
Rating.create(:name => 'cooperate')
Rating.create(:name => 'consider')
Rating.create(:name => 'cost')
Rating.create(:name => 'artistic')
HobbiesRating.create(:hobby_id => '1',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '1',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '1',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '1',:rating_id => '4',:point => '2')
HobbiesRating.create(:hobby_id => '1',:rating_id => '5',:point => '4')
HobbiesRating.create(:hobby_id => '1',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '1',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '1',:rating_id => '8',:point => '3')
HobbiesRating.create(:hobby_id => '1',:rating_id => '9',:point => '3')
HobbiesRating.create(:hobby_id => '1',:rating_id => '10',:point => '3')
HobbiesRating.create(:hobby_id => '1',:rating_id => '11',:point => '2')
HobbiesRating.create(:hobby_id => '2',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '2',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '2',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '2',:rating_id => '4',:point => '3')
HobbiesRating.create(:hobby_id => '2',:rating_id => '5',:point => '5')
HobbiesRating.create(:hobby_id => '2',:rating_id => '6',:point => '2')
HobbiesRating.create(:hobby_id => '2',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '2',:rating_id => '8',:point => '4')
HobbiesRating.create(:hobby_id => '2',:rating_id => '9',:point => '3')
HobbiesRating.create(:hobby_id => '2',:rating_id => '10',:point => '2')
HobbiesRating.create(:hobby_id => '2',:rating_id => '11',:point => '2')
HobbiesRating.create(:hobby_id => '3',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '3',:rating_id => '2',:point => '4')
HobbiesRating.create(:hobby_id => '3',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '3',:rating_id => '4',:point => '3')
HobbiesRating.create(:hobby_id => '3',:rating_id => '5',:point => '4')
HobbiesRating.create(:hobby_id => '3',:rating_id => '6',:point => '2')
HobbiesRating.create(:hobby_id => '3',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '3',:rating_id => '8',:point => '4')
HobbiesRating.create(:hobby_id => '3',:rating_id => '9',:point => '3')
HobbiesRating.create(:hobby_id => '3',:rating_id => '10',:point => '2')
HobbiesRating.create(:hobby_id => '3',:rating_id => '11',:point => '3')
HobbiesRating.create(:hobby_id => '4',:rating_id => '1',:point => '4')
HobbiesRating.create(:hobby_id => '4',:rating_id => '2',:point => '4')
HobbiesRating.create(:hobby_id => '4',:rating_id => '3',:point => '1')
HobbiesRating.create(:hobby_id => '4',:rating_id => '4',:point => '2')
HobbiesRating.create(:hobby_id => '4',:rating_id => '5',:point => '4')
HobbiesRating.create(:hobby_id => '4',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '4',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '4',:rating_id => '8',:point => '2')
HobbiesRating.create(:hobby_id => '4',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '4',:rating_id => '10',:point => '2')
HobbiesRating.create(:hobby_id => '4',:rating_id => '11',:point => '2')
HobbiesRating.create(:hobby_id => '5',:rating_id => '1',:point => '3')
HobbiesRating.create(:hobby_id => '5',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '5',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '5',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '5',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '5',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '5',:rating_id => '7',:point => '4')
HobbiesRating.create(:hobby_id => '5',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '5',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '5',:rating_id => '10',:point => '4')
HobbiesRating.create(:hobby_id => '5',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '6',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '6',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '6',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '6',:rating_id => '4',:point => '3')
HobbiesRating.create(:hobby_id => '6',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '6',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '6',:rating_id => '7',:point => '4')
HobbiesRating.create(:hobby_id => '6',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '6',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '6',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '6',:rating_id => '11',:point => '3')
HobbiesRating.create(:hobby_id => '7',:rating_id => '1',:point => '3')
HobbiesRating.create(:hobby_id => '7',:rating_id => '2',:point => '3')
HobbiesRating.create(:hobby_id => '7',:rating_id => '3',:point => '3')
HobbiesRating.create(:hobby_id => '7',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '7',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '7',:rating_id => '6',:point => '1')
HobbiesRating.create(:hobby_id => '7',:rating_id => '7',:point => '5')
HobbiesRating.create(:hobby_id => '7',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '7',:rating_id => '9',:point => '3')
HobbiesRating.create(:hobby_id => '7',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '7',:rating_id => '11',:point => '2')
HobbiesRating.create(:hobby_id => '8',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '8',:rating_id => '2',:point => '3')
HobbiesRating.create(:hobby_id => '8',:rating_id => '3',:point => '1')
HobbiesRating.create(:hobby_id => '8',:rating_id => '4',:point => '4')
HobbiesRating.create(:hobby_id => '8',:rating_id => '5',:point => '3')
HobbiesRating.create(:hobby_id => '8',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '8',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '8',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '8',:rating_id => '9',:point => '1')
HobbiesRating.create(:hobby_id => '8',:rating_id => '10',:point => '3')
HobbiesRating.create(:hobby_id => '8',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '9',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '9',:rating_id => '2',:point => '2')
HobbiesRating.create(:hobby_id => '9',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '9',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '9',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '9',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '9',:rating_id => '7',:point => '4')
HobbiesRating.create(:hobby_id => '9',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '9',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '9',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '9',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '10',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '10',:rating_id => '2',:point => '2')
HobbiesRating.create(:hobby_id => '10',:rating_id => '3',:point => '1')
HobbiesRating.create(:hobby_id => '10',:rating_id => '4',:point => '4')
HobbiesRating.create(:hobby_id => '10',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '10',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '10',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '10',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '10',:rating_id => '9',:point => '1')
HobbiesRating.create(:hobby_id => '10',:rating_id => '10',:point => '2')
HobbiesRating.create(:hobby_id => '10',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '11',:rating_id => '1',:point => '4')
HobbiesRating.create(:hobby_id => '11',:rating_id => '2',:point => '4')
HobbiesRating.create(:hobby_id => '11',:rating_id => '3',:point => '1')
HobbiesRating.create(:hobby_id => '11',:rating_id => '4',:point => '4')
HobbiesRating.create(:hobby_id => '11',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '11',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '11',:rating_id => '7',:point => '1')
HobbiesRating.create(:hobby_id => '11',:rating_id => '8',:point => '5')
HobbiesRating.create(:hobby_id => '11',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '11',:rating_id => '10',:point => '5')
HobbiesRating.create(:hobby_id => '11',:rating_id => '11',:point => '3')
HobbiesRating.create(:hobby_id => '12',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '12',:rating_id => '2',:point => '1')
HobbiesRating.create(:hobby_id => '12',:rating_id => '3',:point => '3')
HobbiesRating.create(:hobby_id => '12',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '12',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '12',:rating_id => '6',:point => '2')
HobbiesRating.create(:hobby_id => '12',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '12',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '12',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '12',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '12',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '13',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '13',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '13',:rating_id => '3',:point => '5')
HobbiesRating.create(:hobby_id => '13',:rating_id => '4',:point => '1')
HobbiesRating.create(:hobby_id => '13',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '13',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '13',:rating_id => '7',:point => '5')
HobbiesRating.create(:hobby_id => '13',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '13',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '13',:rating_id => '10',:point => '5')
HobbiesRating.create(:hobby_id => '13',:rating_id => '11',:point => '1')
HobbiesRating.create(:hobby_id => '14',:rating_id => '1',:point => '2')
HobbiesRating.create(:hobby_id => '14',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '14',:rating_id => '3',:point => '5')
HobbiesRating.create(:hobby_id => '14',:rating_id => '4',:point => '3')
HobbiesRating.create(:hobby_id => '14',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '14',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '14',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '14',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '14',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '14',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '14',:rating_id => '11',:point => '1')
HobbiesRating.create(:hobby_id => '15',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '3',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '15',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '15',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '15',:rating_id => '8',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '15',:rating_id => '10',:point => '4')
HobbiesRating.create(:hobby_id => '15',:rating_id => '11',:point => '2')
HobbiesRating.create(:hobby_id => '16',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '16',:rating_id => '2',:point => '3')
HobbiesRating.create(:hobby_id => '16',:rating_id => '3',:point => '3')
HobbiesRating.create(:hobby_id => '16',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '16',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '16',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '16',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '16',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '16',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '16',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '16',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '17',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '17',:rating_id => '2',:point => '4')
HobbiesRating.create(:hobby_id => '17',:rating_id => '3',:point => '3')
HobbiesRating.create(:hobby_id => '17',:rating_id => '4',:point => '3')
HobbiesRating.create(:hobby_id => '17',:rating_id => '5',:point => '5')
HobbiesRating.create(:hobby_id => '17',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '17',:rating_id => '7',:point => '4')
HobbiesRating.create(:hobby_id => '17',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '17',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '17',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '17',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '18',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '18',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '18',:rating_id => '3',:point => '4')
HobbiesRating.create(:hobby_id => '18',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '18',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '18',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '18',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '18',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '18',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '18',:rating_id => '10',:point => '5')
HobbiesRating.create(:hobby_id => '18',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '19',:rating_id => '1',:point => '2')
HobbiesRating.create(:hobby_id => '19',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '19',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '19',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '19',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '19',:rating_id => '6',:point => '3')
HobbiesRating.create(:hobby_id => '19',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '19',:rating_id => '8',:point => '4')
HobbiesRating.create(:hobby_id => '19',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '19',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '19',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '20',:rating_id => '1',:point => '4')
HobbiesRating.create(:hobby_id => '20',:rating_id => '2',:point => '3')
HobbiesRating.create(:hobby_id => '20',:rating_id => '3',:point => '5')
HobbiesRating.create(:hobby_id => '20',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '20',:rating_id => '5',:point => '2')
HobbiesRating.create(:hobby_id => '20',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '20',:rating_id => '7',:point => '5')
HobbiesRating.create(:hobby_id => '20',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '20',:rating_id => '9',:point => '5')
HobbiesRating.create(:hobby_id => '20',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '20',:rating_id => '11',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '3',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '5',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '21',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '21',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '21',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '21',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '21',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '22',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '22',:rating_id => '2',:point => '3')
HobbiesRating.create(:hobby_id => '22',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '22',:rating_id => '4',:point => '2')
HobbiesRating.create(:hobby_id => '22',:rating_id => '5',:point => '1')
HobbiesRating.create(:hobby_id => '22',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '22',:rating_id => '7',:point => '2')
HobbiesRating.create(:hobby_id => '22',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '22',:rating_id => '9',:point => '2')
HobbiesRating.create(:hobby_id => '22',:rating_id => '10',:point => '4')
HobbiesRating.create(:hobby_id => '22',:rating_id => '11',:point => '1')
HobbiesRating.create(:hobby_id => '23',:rating_id => '1',:point => '1')
HobbiesRating.create(:hobby_id => '23',:rating_id => '2',:point => '4')
HobbiesRating.create(:hobby_id => '23',:rating_id => '3',:point => '3')
HobbiesRating.create(:hobby_id => '23',:rating_id => '4',:point => '5')
HobbiesRating.create(:hobby_id => '23',:rating_id => '5',:point => '3')
HobbiesRating.create(:hobby_id => '23',:rating_id => '6',:point => '4')
HobbiesRating.create(:hobby_id => '23',:rating_id => '7',:point => '4')
HobbiesRating.create(:hobby_id => '23',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '23',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '23',:rating_id => '10',:point => '2')
HobbiesRating.create(:hobby_id => '23',:rating_id => '11',:point => '4')
HobbiesRating.create(:hobby_id => '24',:rating_id => '1',:point => '5')
HobbiesRating.create(:hobby_id => '24',:rating_id => '2',:point => '5')
HobbiesRating.create(:hobby_id => '24',:rating_id => '3',:point => '2')
HobbiesRating.create(:hobby_id => '24',:rating_id => '4',:point => '2')
HobbiesRating.create(:hobby_id => '24',:rating_id => '5',:point => '5')
HobbiesRating.create(:hobby_id => '24',:rating_id => '6',:point => '5')
HobbiesRating.create(:hobby_id => '24',:rating_id => '7',:point => '3')
HobbiesRating.create(:hobby_id => '24',:rating_id => '8',:point => '1')
HobbiesRating.create(:hobby_id => '24',:rating_id => '9',:point => '4')
HobbiesRating.create(:hobby_id => '24',:rating_id => '10',:point => '1')
HobbiesRating.create(:hobby_id => '24',:rating_id => '11',:point => '2')
Record.create(:user_id => '1',:hobby_id => '1',:time => '4',:date => '2017-09-07',:comment => '')
Record.create(:user_id => '1',:hobby_id => '1',:time => '4',:date => '2017-09-08',:comment => '')
Record.create(:user_id => '1',:hobby_id => '1',:time => '4',:date => '2017-09-09',:comment => '')
Record.create(:user_id => '1',:hobby_id => '2',:time => '4',:date => '2017-09-07',:comment => '')
Record.create(:user_id => '1',:hobby_id => '3',:time => '4',:date => '2017-09-07',:comment => '')
Record.create(:user_id => '1',:hobby_id => '4',:time => '4',:date => '2017-09-07',:comment => '')
Community.create(:hobby_id => '1',:user_id => '1',:name => 'フォーク',:level => '初級',:introduction => '一緒にフォーク習得を目指しましょう')
Community.create(:hobby_id => '1',:user_id => '1',:name => 'カーブボール',:level => '初級',:introduction => 'カーブボールの投げ方を共有しましょう')
Community.create(:hobby_id => '1',:user_id => '1',:name => '速球アップ目指せ120キロ',:level => '初級',:introduction => '一緒に急速アップを目指しましょう')
Community.create(:hobby_id => '1',:user_id => '1',:name => '一本足打法',:level => '初級',:introduction => '王さんのようなフォームを目指して意見交換しましょう')
UsersCommunity.create(:user_id => '1',:community_id => '1')
UsersCommunity.create(:user_id => '1',:community_id => '2')
UsersCommunity.create(:user_id => '1',:community_id => '3')
UsersCommunity.create(:user_id => '1',:community_id => '4')
BoardComment.create(:community_id => '1',:user_id => '1',:comment => 'こんにちは')
BoardComment.create(:community_id => '1',:user_id => '1',:comment => 'こんばんわ')
BoardComment.create(:community_id => '1',:user_id => '1',:comment => 'hello')
BoardComment.create(:community_id => '1',:user_id => '1',:comment => 'よろしく')
FirstStep.create(:hobby_id => '1',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '2',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '20000')
FirstStep.create(:hobby_id => '3',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '4',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')
FirstStep.create(:hobby_id => '5',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '6',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '20000')
FirstStep.create(:hobby_id => '7',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '8',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')
FirstStep.create(:hobby_id => '9',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '10',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '2000')
FirstStep.create(:hobby_id => '11',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '12',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')
FirstStep.create(:hobby_id => '13',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '14',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '20000')
FirstStep.create(:hobby_id => '15',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '16',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')
FirstStep.create(:hobby_id => '17',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '18',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')
FirstStep.create(:hobby_id => '19',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '20',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '20000')
FirstStep.create(:hobby_id => '21',:introduction => '野球の説明',:item => 'ボール／バット／スパイク／ユニフォーム',:cost => '30000')
FirstStep.create(:hobby_id => '22',:introduction => 'サッカーの説明',:item => 'ボール／スパイク／ユニフォーム',:cost => '20000')
FirstStep.create(:hobby_id => '23',:introduction => 'バスケの説明',:item => 'ボール／バッシュ',:cost => '10000')
FirstStep.create(:hobby_id => '24',:introduction => '卓球の説明',:item => 'ラケット',:cost => '3000')